---
- name: Install and Configure MicroK8s on Ubuntu 22.04 VM APP
  hosts: APP
  become: yes

  vars:
    microk8s_addons:
      - dns
      - ingress
      - helm
      - helm3
      - ha-cluster
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - name: Install MicroK8s
      snap:
        name: microk8s
        state: present
        classic: yes

    - name: Add current user to the microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Ensure /var/snap/microk8s/common directory permissions
      file:
        path: /var/snap/microk8s/common
        owner: root
        group: microk8s
        mode: '0775'

    - name: Start MicroK8s service
      command: microk8s start
      become: yes

    - name: Wait for MicroK8s to be ready
      retries: 10
      delay: 30
      command: microk8s status --wait-ready
      register: microk8s_ready
      until: microk8s_ready.rc == 0

    - name: Enable necessary MicroK8s addons
      command: microk8s enable {{ item }}
      loop: "{{ microk8s_addons }}"
      become: yes
      register: enable_addon
      failed_when: "'non-zero return code' in enable_addon.stderr"

    - name: Display MicroK8s status
      command: microk8s status
      become: yes
      register: microk8s_status

    - name: Debug MicroK8s status
      debug:
        var: microk8s_status.stdout_lines

    - name: Ensure .kube directory exists
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Generate MicroK8s kubeconfig
      command: microk8s config
      register: microk8s_config
      changed_when: false
      become: yes

    - name: Copy kubeconfig file for MicroK8s to user's home
      copy:
        content: "{{ microk8s_config.stdout }}"
        dest: "/home/{{ ansible_user }}/.kube/config"
        mode: '0600'
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Change ownership of .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
      become: yes
