---
- name: Install Minikube on Ubuntu 22.04 VM APP
  hosts: APP
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Wait for Docker permissions to take effect
      pause:
        seconds: 10

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Create .kube directory in the specified user's home
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Start Minikube
      command: minikube start --driver=docker
      become: no
      register: minikube_start
      ignore_errors: yes

    - name: Enable ingress addon
      command: minikube addons enable ingress
      become: no
      when: minikube_start is succeeded

    - name: Display Minikube status
      command: minikube status
      become: no
      register: minikube_status

    - name: Debug Minikube status
      debug:
        var: minikube_status.stdout_lines
